### ISSUE TITLE
fail to install for BGQE BG:EE mod is not recognized by EET

### ISSUE THREAD

**Issue by ccharname** [EE-Mod-Setup/EE-Mod-Setup#48]
hello everyone , i try to install eet with ee-mod-setup-tool, but failure mant times
according to the log, it's because the pre-install mods on bgee, BGQE BG:EE mod is not recognized by EET,
should i just remove those mods?

FAILURE:
BGQE BG:EE mod is not recognized by EET, so it can't be imported to BG2:EE with EET
ERROR: [D:/SteamLibrary/steamapps/common/Baldur's Gate Enhanced Edition/WeiDU.log] -> [EET/temp/WeiDU.log] Patching Failed (COPY) (Failure("BGQE BG:EE mod is not recognized by EET, so it can't be imported to BG2:EE with EET"))
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [EET core (resource importation)], rolling back to previous state
Unable to Unlink [EET/backup/0/OTHER.0]: Unix.Unix_error(1, "unlink", "EET/backup/0/OTHER.0")
[EET/backup/0/UNSETSTR.0] SET_STRING uninstall info not found
Will uninstall   1 files for [EET/EET.TP2] component 0.
Uninstalled      1 files for [EET/EET.TP2] component 0.

**Comment by RoxanneSHS** [comment]
The first issue that is obvious is that you tried to install EET in SteamLibrary/steamapps. Never do that since it most always leads to errors as this is a protected directory and steam either blocks or reverts changes made by mods. Sooner or later you always run into trouble - for modding use copies of the game that are in a neutral part of your computer (not steam or programs or windows or such).
EET normally recognises BGQE and imports the changes made to BGEE as if they were part of the original game. 
You can try this: Download https://www.dropbox.com/s/dhv3peewrmq0lnd/compatibility.zip?dl=1 and extract the file. Put it into BG2EE(the directory where EET is extracted) BG2EE/EET/tbl and try EET again.
The better way however is to delete everything and start a clean installation following the instructions in the pdf-file of the install tool.

**Comment by ccharname** [comment]
ok,  i will your advise, thank u.

**Comment by ccharname** [comment]
it works , just move the game from SteamLibrary/steamapps.

**Comment by ccharname** [comment]
> The first issue that is obvious is that you tried to install EET in SteamLibrary/steamapps. Never do that since it most always leads to errors as this is a protected directory and steam either blocks or reverts changes made by mods. Sooner or later you always run into trouble - for modding use copies of the game that are in a neutral part of your computer (not steam or programs or windows or such). EET normally recognises BGQE and imports the changes made to BGEE as if they were part of the original game. You can try this: Download https://www.dropbox.com/s/dhv3peewrmq0lnd/compatibility.zip?dl=1 and extract the file. Put it into BG2EE(the directory where EET is extracted) BG2EE/EET/tbl and try EET again. The better way however is to delete everything and start a clean installation following the instructions in the pdf-file of the install tool.

you done a great job of the ee mod setup tool, thanks
but still a little problem, the tool's download is slow and fallible, even i pre-download all the mods needed, the tool will still do it again(maybe the mod's size is not correct), sometimes will delete pre-download mod and cause missing.
so, could you please just add a Option to skip download process, just checking and provide missing mods?

**Comment by RoxanneSHS** [comment]
Download speed or network behaviour is not something the tool can control. There are up to 5 parallel downloads possible but it depends on where the original mods are hosted.
The main issue with repeated downloads comes from github (many mods are now hosted there) where the toll cannot check for versions prior to download. There is a possibility to skip mod download, it is the red cross prior to the modname on the screen that displays the ongoing downloads - you can disable there and move the mod zip file into the tool's download repository afterwards if you are sure about the version.
