### ISSUE TITLE
 NOT INSTALLED DUE TO ERRORS EET core (EET 2023 message)

### ISSUE THREAD

**Issue by VeezyF** [EE-Mod-Setup/EE-Mod-Setup#59]
I'm trying to install the 2023 EET compilation, removing all the warning associated mods.  When doing so, the following message appears:

----
PLEASE email the file SETUP-EET.DEBUG to K4thos (swit)
Automatically Skipping [EET core (resource importation)] because of error.
Using Language [English]
[.\lang\en_us\dialog.tlk] created, 304010 string entries

NOT INSTALLED DUE TO ERRORS EET core (resource importation)

D:\Steam\steamapps\common\Baldur's Gate II Enhanced Edition>

ERROR: parsing [EET/temp/patch/baf/BDNOREST.baf]: Parsing.Parse_error
ERROR: error compiling [EET/temp/patch/baf/BDNOREST.baf]: Parsing.Parse_error
ERROR: compiling [EET/temp/patch/baf/BDNOREST.baf]!
ERROR: Parsing.Parse_error
Enhanced Edition Trilogy (Enhanced Edition Trilogy) was not installed due to errors.

Without this component the installation cannot be continued.
----
I have the file, where should I send it to?

**Comment by RoxanneSHS** [comment]
The most likely reason for the error is that you use the original game for modding D:\Steam\steamapps\common\
You should always use copies of the game that are in fully accessible sections of your PC, never use steamapps or programs or such since some write errors occur due to access limitation. Your error looks like a classical case of that issue.
The copies must be from unmodded game versions.
