### ISSUE TITLE
Issue with not all options showing up or obscured in Tweaks Anthology

### ISSUE THREAD

**Issue by earthdude67** [EE-Mod-Setup/EE-Mod-Setup#64]
Hi, I'm back to EET after a long hiatus.

I've launched the latest tool and have encountered 2 things with Tweaks Anthology:
1. The 'Bonus Merchants' option isn't available.
2. The 'Romance Cheats' options are all obscured with "Components are not displayed while using batch-installations".  

Thanks in advance!

EDIT: 
Ok, maybe Bonus Merchants is already present in EE and doesn't require a mod to add it in anymore. 
I reviewed the weidu log for cdtweaks and the choices that I would have made for the 'Romance Cheats' were made, so that's good at least.   :)

**Comment by RoxanneSHS** [comment]
1. In EE, the merchants are now in the game already, no cheat required
2. I have restored the missing text in Romance Cheats, it was by error deleted in a recent update, function is there. I have restored the text again, good to see you could work around it.

**Comment by earthdude67** [comment]
I have a general question about updating my installation.If I want to update my installation to make 1 or 2 changes, like Sandrah’s portrait. What’s the best way to do that without having to redo the whole thing?  I tried to do that using the ‘Start_’ tool but it still goes through the entire installation.Thanks!  Sent from my iPhoneOn Feb 13, 2023, at 2:48 AM, Roxanne ***@***.***> wrote:﻿

In EE, the merchants are now in the game already, no cheat required
I have restored the missing text in Romance Cheats, it was by error deleted in a recent update, function is there. I have restored the text again, good to see you could work around it.

**Comment by RoxanneSHS** [comment]
The portrait mod can be just installed manually on top of a finished installation. For any changes, NEVER use the install tool. It is always best done manually, if at all. How to proceed is to be decided on a case to case basis, especially in EET. The route to be taken will depend on the mod to be added, changed or replaced and its dependencies on other mod AND/OR EET itself.

**Comment by earthdude67** [comment]
Hi Roxanne,Question about the Sandrah mod, Haiass specifically.  Every time we change locations Haiass and the main character appear on top of each other and can’t move.  I have to use the console to teleport away.  This is driving me crazy.  How can this be fixed/mitigated?  Can I leave him behind somewhere like other NPCs?Thanks for any insight!Sent from my iPhoneOn Feb 13, 2023, at 4:21 PM, Roxanne ***@***.***> wrote:﻿
The portrait mod can be just installed manually on top of a finished installation. For any changes, NEVER use the install tool. It is always best done manually, if at all. How to proceed is to be decided on a case to case basis, especially in EET. The route to be taken will depend on the mod to be added, changed or replaced and its dependencies on other mod AND/OR EET itself.

**Comment by RoxanneSHS** [comment]
You have some dialogue options (talk to the wolf like to an NPC with the talk-button) to make him stay at a place or move to some location. The issue you describe is to the most extend fixed by the new EE version and new version of the mod. It is possible that some settings in your game have been overwritten by something else. Check in the game options menu if something like "enhanced pathfinding" is activated. If you do not see it or it does not work, you can do this:
- exit the game completely
- in your documents directory (not in game but your central computer files) find a folder Baldur's Gate - Enhanced Edition Trilogy and a file baldur.lua. 
- open the file with any editor (word pad works best)
- look for SetPrivateProfileString('Program Options','Path Search Nodes','400000') if the current value at the end is lower, then change it
- look for SetPrivateProfileString('Game Options','Enhanced Path Search','1') make sure it is 1 = on

In my current EET this works (almost perfect), occasions are very rare when STRG+J is the only solution and it may happen even among NPCs in a party of six.

**Comment by earthdude67** [comment]
The first was set to 32000 and the second option was completely absent.  Strange since I have the version 2.6.6.  I’ve made the changes.  I’ll report back later when I have time to play.Sent from my iPhoneOn Feb 15, 2023, at 7:43 AM, Roxanne ***@***.***> wrote:﻿
You have some dialogue options (talk to the wolf like to an NPC with the talk-button) to make him stay at a place or move to some location. The issue you describe is to the most extend fixed by the new EE version and new version of the mod. It is possible that some settings in your game have been overwritten by something else. Check in the game options menu if something like "enhanced pathfinding" is activated. If you do not see it or it does not work, you can do this:

exit the game completely
in your documents directory (not in game but your central computer files) find a folder Baldur's Gate - Enhanced Edition Trilogy and a file baldur.lua.
open the file with any editor (word pad works best)
look for SetPrivateProfileString('Program Options','Path Search Nodes','400000') if the current value at the end is lower, then change it
look for SetPrivateProfileString('Game Options','Enhanced Path Search','1') make sure it is 1 = on

In my current EET this works (almost perfect), occasions are very rare when STRG+J is the only solution and it may happen even among NPCs in a party of six.

**Comment by RoxanneSHS** [comment]
There is some tool for dialog but I forgot what it was and I never used it myself. I use ConText, a text editor to which some plugins can be added for modding. As reference I use https://weidu.org/~thebigg/README-WeiDU.html and https://gibberlings3.github.io/iesdp/ but mostly to check coding options, otherwise a d-file from a mod can help to see how things are done. (There are tutorials around on some modding sites but sadly they are either outdated or written by self-declared experts that have little knowledge - nothing there that I could recommend.)
