### ISSUE TITLE
Any chance you could add "Endless BG1" and "Convenient Enhanced Edition NPCs"?

### ISSUE THREAD

**Issue by PossuMussoP** [EE-Mod-Setup/EE-Mod-Setup#69]
https://www.gibberlings3.net/mods/other/endlessbg1/

http://www.shsforums.net/files/file/1135-convenient-enhanced-edition-npcs/

Would be great

**Comment by RoxanneSHS** [comment]
endlessbg1 is a Kerzenburg game conversion and as such out of scope.

The "convenient" mod blocks content of many other mods that add to the new EE content which is not only unfair to those modders but also leads to inconsistencies in large mod compilations (if some mods consider EE content to be present while others do not...) The mod may have appeared convenient when EE was still new but by now its content should be considered standard just like that of the original game. Otherwise big modded consistent games per se start to get impossible.
