### ISSUE TITLE
Multiple mods from github downloaded as master.zip

### ISSUE THREAD

**Issue by ameron83** [EE-Mod-Setup/EE-Mod-Setup#7]
I have tried the tool for the first time yesterday and came across this issue:
The mods (or at least some) that are downloaded from github are given filename master.zip instead of a unique name like modName-master.zip, so they overwrite each other and reported as missing after the download phase etc.
I was trying to install mostly "green" mods in a EET installation. Sadly I didn't write down a list of such troublesome mods but if I remember right a couple of examples are Unfinished Business and IylosEET.
Is there a fix / workaround for this?

**Comment by RoxanneSHS** [comment]
This is a random occurance that I have not seen for a long time. It is a github issue and thus out of my reach. It is exactly as you descibe, the github just overwrites a master.zip instead of saving it to the name given. e.g. Save=IylosEET-master.zip. The problem is that github information also overwrites the Tool's internal pre-settings if it happens. This is a double-edged problem because the tool should give priority to the data received by github in order to allow the latest updates available for a mod. The only way I know to work around it is to move the mod data found inside of such a master zip to a secure place and delete the master. If the tool later cannot find the master it will notify you and you can point it to the secured mod folder to use it.

The other way to solve it would be to rename the master.zip to just something else, e.g. master_a.zip and when another one appears call it master_b.zip. Later you tell the tool for extraction which one to use for any mod. The data content inside the zips should be fine, it is really just the names.

 

I have tried several alternatives in the past, including the use of mirrors with fixed names etc. Every alternative in the end creates more trouble in the long run than the current implementation, given that the issue is a random occurance. I know it is cumbersome, but you just had a bad day on github...


Sent: Tuesday, August 06, 2019 at 10:17 AM

**Comment by ameron83** [comment]
Weird that it happens randomly...
Ok I'll give it another try to see if I have better luck, and if not I'll try a workaround you suggested.
Thanks for addressing this!

**Comment by RoxanneSHS** [comment]
Just to mention that you need to download the tool again before reusing because the file names may have been updated to "master" multiple times during the error.
