### ISSUE TITLE
in Fr install some vanilla NPC switch to english in BG1 after installing BGTEE

### ISSUE THREAD

**Issue by sdelanoue** [EE-Mod-Setup/EE-Mod-Setup#81]
Hi, I installed BGTEE with some add-on, all in FR version
but branwen and garrick now have English voice with FR texts, of course in BG1EE alone they speak in FR

int EE-mod-setup I launcher Update EE Mod Setup.vbs and add FR language top of EN

here is my WeiDU.log

[WeiDU.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/11597610/WeiDU.log)

regards,
Stéphane

**Comment by RoxanneSHS** [comment]
You have the BG1NPCs in SoA mod installed. While the new text has French translations to show in the subtitles, there are no French voice files for those NPCs in BG2. So, the things you see would be expected. Also, if I understand correctly, you chose EN + FR in the setup? It should be FR + EN so that the French dialogue.tlk file is used for modding and EN is only used when no FR files exist for a mod.

**Comment by sdelanoue** [comment]
Hi, thank for the answer but no I always put French on top of the list then English, I'll give a try without BG1NPCs in SoA to check is voice is back to french
