### ISSUE TITLE
Cleared Cloakwood Forest Mines as soon as Party floods it Imoen and Sandra Leave the party

### ISSUE THREAD

**Issue by Rothe123** [EE-Mod-Setup/EE-Mod-Setup#87]
any help would be appreciated using the compilation of EET_2023-Selection.ini

**Comment by RoxanneSHS** [comment]
This is not an issue but a feature. Sandrah leaves at that point if you never cared for her quests or opinions etc. You can check that with console (or NearInfinity) C:GetGlobal("sanpoints","Global") -if the value is too low for that point in the game (47), she leaves.
Imoen may leave for some other reason as well.

**Comment by Rothe123** [comment]
oh okay thank you!

**Comment by enderandrew** [comment]
Romanced Sandrah. Was always supportive of her opinions. Did all the quests and cleared every map I could before the Cloakwood Mines. Value is 30 and Sandrah goes from saying she is in love to storming off after I flood the mines (with the slaves having been rescued).

Are you sure there isn't a bug here or something causing the value to be lower than expected at this point?

**Comment by RoxanneSHS** [comment]
You may have solved some vanilla quest in an offensive way or killed somebody you should not have? The points are not just related to her own content but also other quests etc. There may have been some occasion where you lost significantly with her.

**Comment by enderandrew** [comment]
Neither Sandrah (nor any companion) has voiced any displeasure with any quest resolution. I've spared everyone I've had an opportunity to spare. I haven't needlessly killed anyone. I'm playing a LG playthrough. I've also noted she quits right after Cloakwood whether I flood the mines or not.

If the metric is anything 47 or below means you were awful to Sandrah and she hates you enough to leave, then I'm at a loss at how supporting her in every dialogue choice and having her never object to anything only gets you to a 30.

To truly determine if this is a bug or not, I could compare the list of events that get you positive or negative points against my choices and see if they should add up around 30 or where I may have made a bad choice I wasn't aware of.

I'll grep through the folder for "sanpoints" but if these are compiled scripts or binary files, I may not be able to see that in the distributed files.

**Comment by RoxanneSHS** [comment]
Grep should work because everything is compiled only on installation. One chance to miss a lot is when you have not yet done the Demonic Scroll/Waterdeep Visit part prior to Cloakwood.

**Comment by enderandrew** [comment]
I think I've explored basically every map I can before Cloakwood and finished every side quest I can before Cloakwood. I have the Demonic Scroll. Sandrah said early back in Chapter 1 or 2 she would study it and nothing has happened since. I haven't been to Waterdeep. What is supposed to trigger that?

**Comment by enderandrew** [comment]
Okay, I just pulled up a Sandrah walkthrough. Apparently right after I find the scroll, I'm supposed to be directed to Elminster and if I don't do it fast enough, Sandrah is supposed to leave?

I was never directed to go anywhere to meet with Elminister and Sandrah never left. That was Day 3 in my game in Chapter 1. I'm now Day 74 in Chapter 5 and that quest never progressed.

https://imgur.com/a/ueUho4Y

**Comment by RoxanneSHS** [comment]
Most likely you missed Elminster's messenger...a day or so after you discovered and discussed Sandrah's heritage, the messenger appears in an outdoor area out of town. If you moved away too fast or hopped between areas you might have missed him.
You can check with C:GetGlobal("NarQMessApp","GLOBAL"), if it is 1, then the guy probably stands around somewhere in a wilderness and is looking for you. C:CreateCreature("NarQMes") spawns him.

**Comment by enderandrew** [comment]
That was it.

I spawned the messenger, which led to a lot more content. Once completing that content, sanpoints went from 30 to 77.

I guess the Cloakwood trigger is working as intended, but I wonder if Rothe123 ran into the same issue and if there could be some check to make sure you don't miss that messenger since it cuts off so much content in the mod.

**Comment by RoxanneSHS** [comment]
The idea is just the other way round: if you miss (or choose to skip) all those quests, there is no way to re-synchronize the Sandrah story with the main story anymore after Cloakwood (and some later check points). If that is the case, she is supposed to go her own way since anything else would make no more sense. There are many ways through the game but at certain points there needs to be a common ground to continue from.

**Comment by enderandrew** [comment]
I understand that and don't disagree with that.

I'm saying if the messenger is easily missed, and the messenger can be orphaned on some random map, then the player misses most of the content by accident. There should be a check for somehow missing the messenger. Because that is not the player intentionally rejecting the plot.

**Comment by RoxanneSHS** [comment]
Missing a messenger is a common issue, not specific to the mod. Missing Jaheirah's quest or the Umar Hill stronghold notifications happens every now and then. This is no special case here. Keeping the eyes open and avoiding stuff like boots of speed helps but nothing is perfect...
Long cut scenes can help but they break the immersion and flow and many people dislike them as FORCING the plot onto the player and such.
