### ISSUE TITLE
One of the STRATAGEMS mod component is omitted.

### ISSUE THREAD

**Issue by glhfhl** [EE-Mod-Setup/EE-Mod-Setup#94]
I encountered some druids during BG1 at Cloakwood, and they didn't attack at all. 
Just standing while their colleague dying.

Problem was incomplete install of SCS mod.
After manual install, this problem fixed.

The omitted component of EE-mod-setup is this.
~STRATAGEMS/SETUP-STRATAGEMS.TP2~ #0 #6010 // Better calls for help: 34.3

**Comment by RoxanneSHS** [comment]
The component is not compatible with some original game episodes and many mod encounters. It can cause whole cities to get hostile etc. It has not been updated for EE and is therefore not used. The druid behaviour may have another source.

**Comment by glhfhl** [comment]
> The component is not compatible with some original game episodes and many mod encounters. It can cause whole cities to get hostile etc. It has not been updated for EE and is therefore not used. The druid behaviour may have another source.

I think it would be nice for me and other SCS users, if you can make that component color as Red and write some caution note on description like "this specific component can cause serious issues with BGEE". 
Some other hard-to-compatible mods and components are already doing this in BWS, as you know well.

IMO ultimate benefit of using BWS is one touch setup, so it would be nice if i can custom more SCS components by myself without using manual install.

Thank you for the reply.

**Comment by RoxanneSHS** [comment]
There is a one-click option for many mods (those that appear green in the tree) - if you click the mod name, a selected configuration is applied to components. This is for well tested combinations in large installations. There is none for SCS due to the size and neglection of the mod over time - I have some tested combinations in the "compilations" for specific setups but there is no one-size-fits-all for the mod. Experiment as you like at your own peril.
